version: "3.9"
services:
  postgres-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4822914
      - POSTGRES_DB=midsiberia1908
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "midsiberia1908"]
      start_period: 5s
      interval: 5s
